# Site settings
title: "jhu-chang's Space"
url: "jhu-chang.github.io"
highlighter: rouge
paginate: 5
author:
    name: jhu-chang
    github:
    email:
    gitcafe:
    twitter:
    facebook:
    googleplus:
    weibo:
atom_path: /atom.xml
rss_path: /rss.xml

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: 1..6
  enable_coderay: false
  hard_wrap: false
  auto_ids: true
  syntax_highlighter: rouge
permalink: /:categories/:year-:month/:title.html
gems: [jekyll-paginate]

assets_path: /assets
cdn: "//cdn.09hd.com"
sass:
    sass_dir: assets/_sass
    style: :compressed

# comment
comments:
    duoshuo:
        name: jhu-chang
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 26

# 网站统计
analytics:
    baidu:
        siteid:      # 百度统计 js 代码后的字符串

