# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               jhu-chang's blog 
tagline:             'Write ups'
description:         'This is jhu-chang blog post'
url:                 http://jhu-chang.github.io
baseurl:             ''
paginate:            3

# About/contact
author:
  name:              jhu-chang 
  url:               http://jhu-chang.github.io
  email:             gt.jhu.chang@gmail.com

# Custom vars
version:             1.0.0

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: 1..6
  enable_coderay: false
  hard_wrap: false
  auto_ids: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # line_numbers: false # This active all linenos, not good for inline code
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

gems:
  - jekyll-paginate
