# Site settings
title: "jhu-chang's blogs"
url: "//jhu-chang.github.io"
highlighter: rouge
paginate: 5
author:
    name: jhu-chang 
    github:
    email:
    gitcafe:
    twitter:
    facebook:
    googleplus:
    weibo:
atom_path: /atom.xml
rss_path: /rss.xml

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: 1..6
  enable_coderay: false
permalink: /:categories/:year-:month/:title.html
gems: [jekyll-paginate]
exclude: [vendor]
assets_path: /assets
sass:
    sass_dir: assets/_sass
    style: :compressed

# comment
comments:
    duoshuo:
        name:                               # short name
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 26

# tinysou.com
search:
    tinysou:
        engineKey: 

# 网站统计
analytics:
    baidu:
        siteid:                             # 百度统计 js 代码后的字符串

